### ISSUE TITLE
how to run this

### ISSUE THREAD

**Issue by MrMegaMango** [koaning/uvtrick#25]
```
➜ /workspaces/uvtrick (main) $ uv run --with uvtrick --with scikit-learn examples/kmeans.py
Installed 8 packages in 186ms
Traceback (most recent call last):d
  File "/tmp/tmpi8nj__rj/pytemp.py", line 18, in <module>
    args, kwargs = cloudpickle.loads(Path('/tmp/tmpi8nj__rj/pickled_inputs.pickle').read_bytes())
ValueError: unsupported pickle protocol: 5
Traceback (most recent call last):
  File "/workspaces/uvtrick/examples/kmeans.py", line 31, in <module>
    timed = Env(f"scikit-learn=={version}", python=py).run(bench)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.cache/uv/archive-v0/wzWov4QbS1pynQbwmt-Rd/lib/python3.12/site-packages/uvtrick/__init__.py", line 144, in run
    subprocess.run(self.cmd, cwd=temp_dir, check=True)
  File "/home/codespace/.python/current/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['uv', 'run', '--with=cloudpickle', '--quiet', '--with=scikit-learn==0.23', '--python=3.7', '/tmp/tmpi8nj__rj/pytemp.py']' returned non-zero exit status 1.d
```

**Comment by koaning** [comment]
That's ... interesting. Something may have broken while we did the cloudpickle upgrade. Exploring a PR now.

**Comment by koaning** [comment]
Will release a new version now. It seems that it may be related to a numpy version. 

https://github.com/koaning/uvtrick/pull/26
